name: Upload and Deploy

on:
  release:
    types: [published]

jobs:
  upload:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Extend Helper CLI
        uses: elmernocon/accelbyte-extend-github-action@v1

      - name: Upload Image
        env:
          AB_BASE_URL: ${{ secrets.BASE_URL }}
          AB_CLIENT_ID: ${{ secrets.CLIENT_ID }}
          AB_CLIENT_SECRET: ${{ secrets.CLIENT_SECRET }}
        run: |
          extend-helper-cli image-upload \
            --namespace ${{ secrets.NAMESPACE }} \
            --app ${{ secrets.APP }} \
            --image-tag ${{ github.event.release.tag_name }} \
            --login

  deploy:
    runs-on: ubuntu-latest
    needs: upload
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Extend Helper CLI
        uses: elmernocon/accelbyte-extend-github-action@v1

      - name: Deploy App
        env:
          AB_BASE_URL: ${{ secrets.BASE_URL }}
          AB_CLIENT_ID: ${{ secrets.CLIENT_ID }}
          AB_CLIENT_SECRET: ${{ secrets.CLIENT_SECRET }}
        run: |
          extend-helper-cli deploy-app \
            --namespace ${{ secrets.NAMESPACE }} \
            --app ${{ secrets.APP }} \
            --image-tag ${{ github.event.release.tag_name }}
