# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import service_pb2 as service__pb2


class ServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.CreateOrUpdateGuildProgress = channel.unary_unary(
                '/service.Service/CreateOrUpdateGuildProgress',
                request_serializer=service__pb2.CreateOrUpdateGuildProgressRequest.SerializeToString,
                response_deserializer=service__pb2.CreateOrUpdateGuildProgressResponse.FromString,
                )
        self.GetGuildProgress = channel.unary_unary(
                '/service.Service/GetGuildProgress',
                request_serializer=service__pb2.GetGuildProgressRequest.SerializeToString,
                response_deserializer=service__pb2.GetGuildProgressResponse.FromString,
                )


class ServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def CreateOrUpdateGuildProgress(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetGuildProgress(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'CreateOrUpdateGuildProgress': grpc.unary_unary_rpc_method_handler(
                    servicer.CreateOrUpdateGuildProgress,
                    request_deserializer=service__pb2.CreateOrUpdateGuildProgressRequest.FromString,
                    response_serializer=service__pb2.CreateOrUpdateGuildProgressResponse.SerializeToString,
            ),
            'GetGuildProgress': grpc.unary_unary_rpc_method_handler(
                    servicer.GetGuildProgress,
                    request_deserializer=service__pb2.GetGuildProgressRequest.FromString,
                    response_serializer=service__pb2.GetGuildProgressResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'service.Service', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class Service(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def CreateOrUpdateGuildProgress(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/service.Service/CreateOrUpdateGuildProgress',
            service__pb2.CreateOrUpdateGuildProgressRequest.SerializeToString,
            service__pb2.CreateOrUpdateGuildProgressResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetGuildProgress(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/service.Service/GetGuildProgress',
            service__pb2.GetGuildProgressRequest.SerializeToString,
            service__pb2.GetGuildProgressResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
